// automatically generated by the FlatBuffers compiler, do not modify

package com.company.flatbuf;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Employees extends Table {
  public static Employees getRootAsEmployees(ByteBuffer _bb) { return getRootAsEmployees(_bb, new Employees()); }
  public static Employees getRootAsEmployees(ByteBuffer _bb, Employees obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public Employees __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Employee employees(int j) { return employees(new Employee(), j); }
  public Employee employees(Employee obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int employeesLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }

  public static int createEmployees(FlatBufferBuilder builder,
      int employeesOffset) {
    builder.startObject(1);
    Employees.addEmployees(builder, employeesOffset);
    return Employees.endEmployees(builder);
  }

  public static void startEmployees(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addEmployees(FlatBufferBuilder builder, int employeesOffset) { builder.addOffset(0, employeesOffset, 0); }
  public static int createEmployeesVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startEmployeesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endEmployees(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishEmployeesBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedEmployeesBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }
}

